title: UNCSS
description: Understudied Networks in Computational Social Science
baseurl: "" # Lascialo vuoto se usi username.github.io
url: "https://galeale.github.io/UNCSS" # Sostituisci username con il tuo nome utente GitHub

remote_theme: hydecorp/hydejack@v9.2.1
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

menu:
  - title: Submit your contribution
    url:   /submission/
  - title: Program
    url:   /program/
  - title: Organizers
    url:   /organizers/
